### PR TITLE
Fix #584 follow link if path prefix is symlink.

### LINKED ISSUE #584: Error occure FileNotFoundException File input plugin, if Just under symbolic link file.
Hello.

Error occure FileNotFoundException file input plugin, Just under symbolic link file.
We use Embulk v0.8.18.

`/apps/embulk-test/current/shared_generated` is symbolic link directory.

## NG
```
in:
  type: file
  path_prefix: /apps/embulk-test/current/shared_generated/test.csv
  parser:
    type: csv
    delimiter: ","
    columns:
      - {name: title, type: string }
      - {name: company_id, type: long }
      - {name: company_name, type: string }
      - {name: url, type: string }

```

But if Not Just under is OK.
This example is under symbolic link has subdirectory.

## OK

```
in:
  type: file
  path_prefix: /apps/embulk-test/current/shared_generated/subdirectory/test.csv
  parser:
    type: csv
    delimiter: ","
    columns:
      - {name: title, type: string }
      - {name: company_id, type: long }
      - {name: company_name, type: string }
      - {name: url, type: string }

```

## stacktrace
```
2017-03-30 11:35:18.013 +0900: Embulk v0.8.18
2017-03-30 11:35:21.258 +0900 [INFO] (0001:transaction): Listing local files at directory '/apps/embulk-test/current/shared_generated' filtering filename by prefix 'test.csv'
2017-03-30 11:35:21.268 +0900 [INFO] (0001:transaction): Loading files [/apps/embulk-test/current/shared_generated]
2017-03-30 11:35:21.385 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / output tasks 4 = input tasks 1 * 4
2017-03-30 11:35:21.398 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2017-03-30 11:35:21.512 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: java.io.FileNotFoundException: /apps/embulk-test/current/shared_generated (Is a directory)
  at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(org/embulk/exec/BulkLoader.java:373)
  at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:591)
  at org.embulk.exec.BulkLoader.access$000(org/embulk/exec/BulkLoader.java:33)
  at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:389)
  at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:385)
  at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
  at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:385)
  at org.embulk.EmbulkEmbed.run(org/embulk/EmbulkEmbed.java:180)
  at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
  at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:453)
  at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:314)
  at RUBY.run(uri:classloader:/embulk/runner.rb:84)
  at RUBY.run(uri:classloader:/embulk/command/embulk_run.rb:307)
  at RUBY.<main>(uri:classloader:/embulk/command/embulk_main.rb:2)
  at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:850)
  at org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2976)
  at org.jruby.RubyKernel.requireCommon(org/jruby/RubyKernel.java:963)
  at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:956)
  at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen)
  at Users.toyama_minus_h.bin.embulk.embulk.command.embulk_bundle.invokeOther35:require(Users/toyama_minus_h/bin/embulk/embulk/command/file:/Users/toyama-h/bin/embulk!/embulk/command/embulk_bundle.rb:30)
  at Users.toyama_minus_h.bin.embulk.embulk.command.embulk_bundle.<main>(file:/Users/toyama-h/bin/embulk!/embulk/command/embulk_bundle.rb:30)
  at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:627)
  at org.jruby.Ruby.runScript(org/jruby/Ruby.java:834)
  at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:749)
  at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:767)
  at org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:580)
  at org.jruby.Main.doRunFromMain(org/jruby/Main.java:425)
  at org.jruby.Main.internalRun(org/jruby/Main.java:313)
  at org.jruby.Main.run(org/jruby/Main.java:242)
  at org.jruby.Main.main(org/jruby/Main.java:204)
  at org.embulk.cli.Main.main(org/embulk/cli/Main.java:23)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /apps/embulk-test/current/shared_generated (Is a directory)
  at org.embulk.spi.util.InputStreamFileInput.nextFile(InputStreamFileInput.java:170)
  at org.embulk.spi.util.FileInputInputStream.nextFile(FileInputInputStream.java:27)
  at org.embulk.spi.util.LineDecoder.nextFile(LineDecoder.java:52)
  at org.embulk.standards.CsvTokenizer.nextFile(CsvTokenizer.java:108)
  at org.embulk.standards.CsvParserPlugin.run(CsvParserPlugin.java:242)
  at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:153)
  at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:294)
  at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$000(LocalExecutorPlugin.java:212)
  at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:257)
  at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:253)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /apps/embulk-test/current/shared_generated (Is a directory)
  at java.io.FileInputStream.open0(Native Method)
  at java.io.FileInputStream.open(FileInputStream.java:195)
  at java.io.FileInputStream.<init>(FileInputStream.java:138)
  at org.embulk.standards.LocalFileInputPlugin$2.open(LocalFileInputPlugin.java:188)
  at org.embulk.spi.util.InputStreamFileInput$OpenerProvider.openNext(InputStreamFileInput.java:74)
  at org.embulk.spi.util.InputStreamFileInput.nextFile(InputStreamFileInput.java:167)
  ... 13 more

```

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
Fix #584 follow a link if path prefix is symlink.

### CODE REVIEW

**Comment by toyama0919** [comment]
@hiroyuki-sato 
Oh, thanks!

**Comment by hiroyuki-sato** [comment]
@dmikurube Please take a look this PR. 

I'm wondering current implementation does not follow symbolic link directory. 
If so, this change will break current compatibility. 

The following is the reproduce steps.

## After patch applied

```
./pkg/embulk-0.8.18.jar preview /path/to/config.yml
+---------+--------------+-------------------------+-------------------------+----------------------------+
| id:long | account:long |          time:timestamp |      purchase:timestamp |             comment:string |
+---------+--------------+-------------------------+-------------------------+----------------------------+
|       1 |       32,864 | 2015-01-27 19:23:49 UTC | 2015-01-27 00:00:00 UTC |                     embulk |
|       2 |       14,824 | 2015-01-27 19:01:23 UTC | 2015-01-27 00:00:00 UTC |               embulk jruby |
|       3 |       27,559 | 2015-01-28 02:20:02 UTC | 2015-01-28 00:00:00 UTC | Embulk "csv" parser plugin |
|       4 |       11,270 | 2015-01-29 11:54:36 UTC | 2015-01-29 00:00:00 UTC |                            |
+---------+--------------+-------------------------+-------------------------+----------------------------+
```


## Reproduce steps.

### create example

```
embulk example foo
2017-03-30 17:29:04.620 +0900: Embulk v0.8.18
Creating foo directory...
  Creating foo/
  Creating foo/csv/
  Creating foo/csv/sample_01.csv.gz
  Creating foo/seed.yml

Run following subcommands to try embulk:

   1. embulk guess foo/seed.yml -o config.yml
   2. embulk preview config.yml
   3. embulk run config.yml
```

```
embulk guess foo/seed.yml -o config.yml
```

### OK Case

```
embulk preview config.yml
+---------+--------------+-------------------------+-------------------------+----------------------------+
| id:long | account:long |          time:timestamp |      purchase:timestamp |             comment:string |
+---------+--------------+-------------------------+-------------------------+----------------------------+
|       1 |       32,864 | 2015-01-27 19:23:49 UTC | 2015-01-27 00:00:00 UTC |                     embulk |
|       2 |       14,824 | 2015-01-27 19:01:23 UTC | 2015-01-27 00:00:00 UTC |               embulk jruby |
|       3 |       27,559 | 2015-01-28 02:20:02 UTC | 2015-01-28 00:00:00 UTC | Embulk "csv" parser plugin |
|       4 |       11,270 | 2015-01-29 11:54:36 UTC | 2015-01-29 00:00:00 UTC |                            |
+---------+--------------+-------------------------+-------------------------+----------------------------+
```

### NG Case test make symlink directory

```
% cd foo
% ln -s csv csv_symlink
% cd ..
```

edit config.yml. Change `path_prefix` to symlink directory. 

```yaml
in:
  type: file
#  path_prefix: /path/to/foo/csv/sample_
  path_prefix: /path/to/foo/csv_symlink/sample_
  decoders:
  - {type: gzip}
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
out: {type: stdout}
```

### Run preview

```
% embulk preview config.yml
2017-03-30 17:30:06.808 +0900: Embulk v0.8.18
2017-03-30 17:30:07.804 +0900 [INFO] (0001:preview): Listing local files at directory '/path/to/foo/csv_symlink' filtering filename by prefix 'sample_'
2017-03-30 17:30:07.808 +0900 [INFO] (0001:preview): Loading files [/path/to/foo/csv_symlink]
java.lang.RuntimeException: java.io.FileNotFoundException: /path/to/foo/csv_symlink (Is a directory)
	at org.embulk.spi.util.InputStreamFileInput.nextFile(org/embulk/spi/util/InputStreamFileInput.java:170)
	at org.embulk.exec.SamplingParserPlugin.readSample(org/embulk/exec/SamplingParserPlugin.java:160)
	at org.embulk.exec.SamplingParserPlugin.readSample(org/embulk/exec/SamplingParserPlugin.java:155)
	at org.embulk.exec.SamplingParserPlugin.run(org/embulk/exec/SamplingParserPlugin.java:144)
	at org.embulk.spi.FileInputRunner.run(org/embulk/spi/FileInputRunner.java:153)
	at org.embulk.exec.SamplingParserPlugin$1.run(org/embulk/exec/SamplingParserPlugin.java:44)
	at org.embulk.spi.FileInputRunner$RunnerControl$1$1.run(org/embulk/spi/FileInputRunner.java:123)
	at org.embulk.exec.SamplingParserPlugin.transaction(org/embulk/exec/SamplingParserPlugin.java:137)
	at org.embulk.spi.FileInputRunner$RunnerControl$1.run(org/embulk/spi/FileInputRunner.java:117)
	at org.embulk.spi.util.Decoders$RecursiveControl.transaction(org/embulk/spi/util/Decoders.java:77)
	at org.embulk.spi.util.Decoders.transaction(org/embulk/spi/util/Decoders.java:33)
	at org.embulk.spi.FileInputRunner$RunnerControl.run(org/embulk/spi/FileInputRunner.java:114)
	at org.embulk.standards.LocalFileInputPlugin.resume(org/embulk/standards/LocalFileInputPlugin.java:79)
	at org.embulk.standards.LocalFileInputPlugin.transaction(org/embulk/standards/LocalFileInputPlugin.java:69)
	at org.embulk.spi.FileInputRunner.transaction(org/embulk/spi/FileInputRunner.java:65)
	at org.embulk.exec.SamplingParserPlugin.runFileInputSampling(org/embulk/exec/SamplingParserPlugin.java:34)
	at org.embulk.exec.PreviewExecutor.doPreview(org/embulk/exec/PreviewExecutor.java:96)
	at org.embulk.exec.PreviewExecutor.access$000(org/embulk/exec/PreviewExecutor.java:30)
	at org.embulk.exec.PreviewExecutor$1.run(org/embulk/exec/PreviewExecutor.java:70)
	at org.embulk.exec.PreviewExecutor$1.run(org/embulk/exec/PreviewExecutor.java:66)
	at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
	at org.embulk.exec.PreviewExecutor.preview(org/embulk/exec/PreviewExecutor.java:66)
	at org.embulk.EmbulkEmbed.preview(org/embulk/EmbulkEmbed.java:169)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:453)
	at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:314)
	at RUBY.preview(/Users/hsato/.embulk/bin/embulk!/embulk/runner.rb:35)
	at RUBY.run(/Users/hsato/.embulk/bin/embulk!/embulk/command/embulk_run.rb:305)
	at RUBY.<main>(/Users/hsato/.embulk/bin/embulk!/embulk/command/embulk_main.rb:2)
	at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:850)
	at org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2976)
	at org.jruby.RubyKernel.requireCommon(org/jruby/RubyKernel.java:963)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:956)
	at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen)
	at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
	at Users.hsato.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(Users/hsato/$_dot_embulk/bin/embulk/embulk/command/file:/Users/hsato/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at Users.hsato.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.<main>(file:/Users/hsato/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:627)
	at org.jruby.Ruby.runScript(org/jruby/Ruby.java:834)
	at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:749)
	at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:767)
	at org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:580)
	at org.jruby.Main.doRunFromMain(org/jruby/Main.java:425)
	at org.jruby.Main.internalRun(org/jruby/Main.java:313)
	at org.jruby.Main.run(org/jruby/Main.java:242)
	at org.jruby.Main.main(org/jruby/Main.java:204)
	at org.embulk.cli.Main.main(org/embulk/cli/Main.java:23)
Caused by: java.io.FileNotFoundException: /path/to/foo/csv_symlink (Is a directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.embulk.standards.LocalFileInputPlugin$2.open(LocalFileInputPlugin.java:188)
	at org.embulk.spi.util.InputStreamFileInput$OpenerProvider.openNext(InputStreamFileInput.java:74)
	at org.embulk.spi.util.InputStreamFileInput.nextFile(InputStreamFileInput.java:167)
	at org.embulk.exec.SamplingParserPlugin.readSample(SamplingParserPlugin.java:160)
	at org.embulk.exec.SamplingParserPlugin.readSample(SamplingParserPlugin.java:155)
	at org.embulk.exec.SamplingParserPlugin.run(SamplingParserPlugin.java:144)
	at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:153)
	at org.embulk.exec.SamplingParserPlugin$1.run(SamplingParserPlugin.java:44)
	at org.embulk.spi.FileInputRunner$RunnerControl$1$1.run(FileInputRunner.java:123)
	at org.embulk.exec.SamplingParserPlugin.transaction(SamplingParserPlugin.java:137)
	at org.embulk.spi.FileInputRunner$RunnerControl$1.run(FileInputRunner.java:117)
	at org.embulk.spi.util.Decoders$RecursiveControl.transaction(Decoders.java:77)
	at org.embulk.spi.util.Decoders.transaction(Decoders.java:33)
	at org.embulk.spi.FileInputRunner$RunnerControl.run(FileInputRunner.java:114)
	at org.embulk.standards.LocalFileInputPlugin.resume(LocalFileInputPlugin.java:79)
	at org.embulk.standards.LocalFileInputPlugin.transaction(LocalFileInputPlugin.java:69)
	at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:65)
	at org.embulk.exec.SamplingParserPlugin.runFileInputSampling(SamplingParserPlugin.java:34)
	at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:96)
	at org.embulk.exec.PreviewExecutor.access$000(PreviewExecutor.java:30)
	at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:70)
	at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:66)
	at org.embulk.spi.Exec.doWith(Exec.java:25)
	at org.embulk.exec.PreviewExecutor.preview(PreviewExecutor.java:66)
	at org.embulk.EmbulkEmbed.preview(EmbulkEmbed.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:453)
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:314)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:46)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:90)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:214)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:200)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:205)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:358)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:195)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:112)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:99)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:35)
	at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
	at org.jruby.Ruby.runInterpreter(Ruby.java:850)
	at org.jruby.Ruby.loadFile(Ruby.java:2976)
	at org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:243)
	at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:34)
	at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:885)
	at org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:525)
	at org.jruby.runtime.load.LoadService.require(LoadService.java:396)
	at org.jruby.RubyKernel.requireCommon(RubyKernel.java:963)
	at org.jruby.RubyKernel.require19(RubyKernel.java:956)
	at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(RubyKernel$INVOKER$s$1$0$require19.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:383)
	at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at Users.hsato.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(file:/Users/hsato/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at Users.hsato.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.RUBY$script(file:/Users/hsato/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.jruby.ir.Compiler$1.load(Compiler.java:111)
	at org.jruby.Ruby.runScript(Ruby.java:834)
	at org.jruby.Ruby.runNormally(Ruby.java:749)
	at org.jruby.Ruby.runNormally(Ruby.java:767)
	at org.jruby.Ruby.runFromMain(Ruby.java:580)
	at org.jruby.Main.doRunFromMain(Main.java:425)
	at org.jruby.Main.internalRun(Main.java:313)
	at org.jruby.Main.run(Main.java:242)
	at org.jruby.Main.main(Main.java:204)
	at org.embulk.cli.Main.main(Main.java:23)

Error: java.io.FileNotFoundException: /path/to/foo/csv_symlink (Is a directory)
```

**Comment by dmikurube** [comment]
@hiroyuki-sato Compatibility is worth considering. What do you think to have a configuration `follow_symlinks` to control the behavior?

**Comment by hiroyuki-sato** [comment]
## Test directory layout.

```
csv
|-- dir1
|   `-- sample_01.csv.gz
`-- dir2 -> dir1

2 directories, 1 file
```

## Current implementation. 

If a symlink exists in a subdirectory, it raises an exception. 

IMO, It's a bug. 

## Solution 

* Plan A: Always follow a symlink. (current PR)
* Plan B: Add `follow_symlinks` configuration option. 
  * `follow_symlinks` false: Skip symblic directory.
  * `follow_symlinks` true: Follow symlink. 

Due to current implementation behavior, probably nobody uses symlink in the data directory. 
That's why I think Plan A is OK. 
How do you think?

**Comment by hiroyuki-sato** [comment]
And for my Java skill, I can't implement Plan B immediately. :cry:

**Comment by hiroyuki-sato** [comment]
@dmikurube 

I wrote `follow_symlink` option version. 
Which is better? 
https://github.com/hiroyuki-sato/embulk/commit/f9b5baa5c6bf17d3964c8889c303490d7d8a4da5

And do you know how to create the empty set at this part?
https://github.com/hiroyuki-sato/embulk/commit/f9b5baa5c6bf17d3964c8889c303490d7d8a4da5#diff-cd7e0cf53a7c6a54ad50ce82d4680196R139

**Comment by muga** [comment]
It's good to me. Can you rename the option with "follow_symlinks"?

**Comment by hiroyuki-sato** [comment]
@muga Thank you for the comment.

I renamed the option name with `follow_symlinks`.

PTAL. 



## Test

### Directories layout

```
hoge
|-- csv
|   |-- dir1
|   |   `-- sample_01.csv.gz
|   `-- dir2 -> dir1
`-- seed.yml

3 directories, 2 files
```

```yaml
in:
  type: file
  path_prefix: /private/tmp/hoge/csv
#  follow_symlinks: true
  decoders:
  - {type: gzip}
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
out: {type: stdout}
```

### `follow_symlinks`: false (default)

```
2017-04-01 22:16:32.265 +0900 [INFO] (0001:transaction): Listing local files at directory '/private/tmp/hoge/csv' filtering filename by prefix ''
2017-04-01 22:16:32.274 +0900 [INFO] (0001:transaction): Loading files [/private/tmp/hoge/csv/dir1/sample_01.csv.gz]
2017-04-01 22:16:32.355 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / output tasks 4 = input tasks 1 * 4
2017-04-01 22:16:32.365 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
1,32864,2015-01-27 19:23:49,20150127,embulk
2,14824,2015-01-27 19:01:23,20150127,embulk jruby
3,27559,2015-01-28 02:20:02,20150128,Embulk "csv" parser plugin
4,11270,2015-01-29 11:54:36,20150129,
2017-04-01 22:16:32.675 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2017-04-01 22:16:32.683 +0900 [INFO] (main): Committed.
2017-04-01 22:16:32.683 +0900 [INFO] (main): Next config diff: {"in":{"last_path":"/private/tmp/hoge/csv/dir1/sample_01.csv.gz"},"out":{}}
```

### `follow_symlinks`: true 

```
2017-04-01 22:17:12.654 +0900: Embulk v0.8.18
2017-04-01 22:17:25.713 +0900 [INFO] (0001:transaction): Listing local files at directory '/private/tmp/hoge/csv' filtering filename by prefix ''
2017-04-01 22:17:25.726 +0900 [INFO] (0001:transaction): Loading files [/private/tmp/hoge/csv/dir1/sample_01.csv.gz, /private/tmp/hoge/csv/dir2/sample_01.csv.gz]
2017-04-01 22:17:25.874 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / output tasks 4 = input tasks 2 * 2
2017-04-01 22:17:25.897 +0900 [INFO] (0001:transaction): {done:  0 / 2, running: 0}
1,32864,2015-01-27 19:23:49,20150127,embulk
1,32864,2015-01-27 19:23:49,20150127,embulk
2,14824,2015-01-27 19:01:23,20150127,embulk jruby
2,14824,2015-01-27 19:01:23,20150127,embulk jruby
3,27559,2015-01-28 02:20:02,20150128,Embulk "csv" parser plugin
3,27559,2015-01-28 02:20:02,20150128,Embulk "csv" parser plugin
4,11270,2015-01-29 11:54:36,20150129,
4,11270,2015-01-29 11:54:36,20150129,
2017-04-01 22:17:26.271 +0900 [INFO] (0001:transaction): {done:  2 / 2, running: 0}
2017-04-01 22:17:26.271 +0900 [INFO] (0001:transaction): {done:  2 / 2, running: 0}
2017-04-01 22:17:26.283 +0900 [INFO] (main): Committed.
2017-04-01 22:17:26.284 +0900 [INFO] (main): Next config diff: {"in":{"last_path":"/private/tmp/hoge/csv/dir2/sample_01.csv.gz"},"out":{}}
```

**Comment by hiroyuki-sato** [comment]
@muga 

Do I need to execute `Reformat code` and `Optimize imports`?
https://github.com/hiroyuki-sato/embulk/commit/7d7c4a516293310436e564ebc02562b6ce7f1e87

File: embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java [hunk 1]
```diff
@@ -43,6 +47,10 @@
         @ConfigDefault("null")
         Optional<String> getLastPath();
 
+        @Config("follow_symlinks")
+        @ConfigDefault("false")
+        Boolean getFollowSymlinks();
```
Comment (muga) [inline embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java]: "boolean" is better than "Boolean" as the return type in general. Do you have any reasons why you use it?

File: embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java [hunk 2]
```diff
@@ -148,6 +165,13 @@ public FileVisitResult preVisitDirectory(Path path, BasicFileAttributes attrs)
                 @Override
                 public FileVisitResult visitFile(Path path, BasicFileAttributes attrs)
                 {
+                    try {
+                        if(  Files.isDirectory(path.toRealPath()) ) {
+                            return FileVisitResult.CONTINUE;
+                        }
+                    } catch (IOException ex){
+                        new Throwable(ex);
```
Comment (muga) [inline embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java]: Please use `RuntimeException` like:
```
throw new RuntimeException("reason", ex);
```

File: embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java [hunk 3]
```diff
@@ -148,6 +165,13 @@ public FileVisitResult preVisitDirectory(Path path, BasicFileAttributes attrs)
                 @Override
                 public FileVisitResult visitFile(Path path, BasicFileAttributes attrs)
                 {
+                    try {
+                        if(  Files.isDirectory(path.toRealPath()) ) {
+                            return FileVisitResult.CONTINUE;
+                        }
```
Comment (muga) [inline embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java]: Can you explain and comment what you meant? It would be helpful for maintaining the code.

**Comment by hiroyuki-sato** [comment]
Is your question why the `follow_symlinks` option is `false` by default?
Is this correct?

I think the following 

* Current implementation raises an exception when a file is a symbolic link(point to a directory). 
* So currently, it **can't** follow the symbolic link. 
* That's why I set default option to `false`.

But I have no objection that the `follow_symlinks` option change to `true` by default. 
I think it is comfortable for many users.

File: embulk-docs/src/built-in.rst [hunk 4]
```diff
@@ -128,17 +128,19 @@ The ``file`` input plugin reads files from local file system.
...
++=================+==========+================================================+======================+
+| path\_prefix    | string   | Path prefix of input files                     | required             |
++-----------------+----------+------------------------------------------------+----------------------+
+| parsers         | hash     | Parsers configurations (see below)             | required             |
++-----------------+----------+------------------------------------------------+----------------------+
+| decoders        | array    | Decoder configuration (see below)              |                      |
++-----------------+----------+------------------------------------------------+----------------------+
+| last\_path      | string   | Name of last read file in previous operation   |                      |
++-----------------+----------+------------------------------------------------+----------------------+
+| follow_symlinks | boolean  | Follow symbolic link directories               | ``false`` by default |
```
Comment (dmikurube) [inline embulk-docs/src/built-in.rst]: `\_` may be needed as `last\_path`.

Comment (dmikurube) [inline embulk-docs/src/built-in.rst]: Is this following only symbolic link "directories"? The definition of `FOLLOW_LINKS` does not say so.
http://docs.oracle.com/javase/jp/7/api/java/nio/file/FileVisitOption.html#FOLLOW_LINKS

I'd suggest `If true, follow symbolic links` for this.

File: embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java [hunk 5]
```diff
@@ -30,6 +30,10 @@
 import org.embulk.spi.util.InputStreamTransactionalFileInput;
 import org.slf4j.Logger;
 
+import java.nio.file.FileVisitOption;
+import java.util.Set;
+import java.util.EnumSet;
```
Comment (dmikurube) [inline embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java]: nit: reorder alphabetically.

File: embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java [hunk 6]
```diff
@@ -148,6 +165,13 @@ public FileVisitResult preVisitDirectory(Path path, BasicFileAttributes attrs)
                 @Override
                 public FileVisitResult visitFile(Path path, BasicFileAttributes attrs)
                 {
+                    try {
+                        if(  Files.isDirectory(path.toRealPath()) ) {
```
Comment (dmikurube) [inline embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java]: nit: follow the same coding style:
```
if (Files.isDirectory(...)) {
```

**Comment by hiroyuki-sato** [comment]
@muga @dmikurube Thank you for the comment.
Forgive me my poor English. 
First, let's summarize **current** behavior. 

* Symbolic link file point to file only: open it.
* Symbolic link file point to a directory: raise an exception.

## Config file.

```yaml
in:
  type: file
  path_prefix: /private/tmp/link_sample/csv
  decoders:
  - {type: gzip}
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
out: {type: stdout}
```

## Case1: A symbolic link points to regular files only. 

```
link_sample/csv/
|-- dir1
|   |-- sample_01.csv.gz
|   |-- sample_02.csv.gz -> sample_01.csv.gz
|   `-- sample_03.csv.gz -> /tmp/sample_03.csv.gz
```

```
2017-04-03 16:16:06.619 +0900 [INFO] (0001:transaction): Loading files [/private/tmp/link_sample/csv/dir1/sample_01.csv.gz, /private/tmp/link_sample/csv/dir1/sample_02.csv.gz, /private/tmp/link_sample/csv/dir1/sample_03.csv.gz]
...
```

This case works correctly.

* `sample_02.csv.gz` and `sample_03.csv.gz` are symbolic files.
* Load all files even a input data is symbolic link file. 

## Case2: A symbolic link file point to directory and files. 

```
link_sample/csv
|-- dir1
|   |-- sample_01.csv.gz
|   |-- sample_02.csv.gz -> sample_01.csv.gz
|   `-- sample_03.csv.gz -> /tmp/sample_03.csv.gz
`-- dir2 -> dir1
```

```
2017-04-03 16:20:12.628 +0900 [INFO] (0001:transaction): Loading files [/private/tmp/link_sample/csv/dir1/sample_01.csv.gz, /private/tmp/link_sample/csv/dir1/sample_02.csv.gz, /private/tmp/link_sample/csv/dir1/sample_03.csv.gz, /private/tmp/link_sample/csv/dir2]
...
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: java.io.FileNotFoundException: /private/tmp/link_sample/csv/dir2 (Is a directory)
	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(org/embulk/exec/BulkLoader.java:373)
	at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:591)
	at org.embulk.exec.BulkLoader.access$000(org/embulk/exec/BulkLoader.java:33)
```

* Set loading files `/private/tmp/link_sample/csv/dir2`(symbolic link(direcotry)) as input data. 
* When the `dir2` try to open, raise an Exception `java.io.FileNotFoundException`.

That's why current implementation **can't** follow a symbolic link (point to **directory**).

**Comment by muga** [comment]
@dmikurube @hiroyuki-sato thank you for summarizing. First `follow_symlinks==false` is incompatible with the current behavior. The current behavior throws FileNotFoundException, Embulk stops and then any data are not ingested.

The current `follow_symlinks==false` behavior skips visiting symlinks of directories. If the specified path_prefix includes non-symlinked files and symlinks of directories, the PR enables ingesting data non-symlinked files. Because symlinks of directories are ignored.

This behavior is not small change. it's better to keep backward compatibility with the current behavior.

**Comment by dmikurube** [comment]
Sorry, I'm still confused. What "current" means? I meant the existing `master`'s `HEAD` by "current", but others meant different...

Let's talk with "existing" and "proposed". Sorry about that.

**Comment by hiroyuki-sato** [comment]
Sorry for the confusion.
Current = v0.8.18 
I'll use the word **latest release** or write version explicitly. 

I changed the words at previous posts.

**Comment by dmikurube** [comment]
Okay, thanks. Then, I don't understand why the proposed `follow_symlinks==false` is incompatible with the existing behavior from the code.

From https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#walkFileTree(java.nio.file.Path,%20java.nio.file.FileVisitor), the existing `Files.walkFileTree(directory, new SimpleFileVisitor<Path>...` is the same with non-`FOLLOW_LINKS`. Then, it looks to me that the proposed `follow_symlinks==false` is compatible with the existing, and `follow_symlinks==true` is the new behavior. 

We may need to make it clear what we're fixing...

File: embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java (hunk 1 above)
Comment (hiroyuki-sato) [inline embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java]: Changed `Boolean` to `boolean`

File: embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java (hunk 3 above)
Comment (hiroyuki-sato) [inline embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java]: Added comments.

File: embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java (hunk 2 above)
Comment (hiroyuki-sato) [inline embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java]: Use RuntimeException. I'm worried "reason" is correctly or not.

File: embulk-docs/src/built-in.rst (hunk 4 above)
Comment (hiroyuki-sato) [inline embulk-docs/src/built-in.rst]: Added `\`

Comment (hiroyuki-sato) [inline embulk-docs/src/built-in.rst]: Changed `true` by default and message `If true, follow symbolic links`.

**Comment by hiroyuki-sato** [comment]
@dmikurube about code formatting. 
I always use `Reformat code` and `Optimize imports` in the IntelliJ IDE. 

If you it's OK, I'll apply this change. 
The format is Airlift, I'm OK to change another style if #582 resolved.
https://github.com/hiroyuki-sato/embulk/commit/8b30653defdeef3044a3ee5849838a34ac079e35

If I should change code format after #582 resolved, I'll modify the code minimize

**Comment by dmikurube** [comment]
@hiroyuki-sato We should at least separate PRs of behavior changes and refactoring including cleanups and reformatting for healthy code reviews. Such reformatting PRs will be welcome (when we decide), but let's do in another PR.

**Comment by hiroyuki-sato** [comment]
@dmikurube OK, I don't clean up and reformat code in this PR.

**Comment by hiroyuki-sato** [comment]
## Compatible or Incompatible.

* The following viewpoint, I think this change is incompatible. 
  * `Files.walkFileTree(directory, new SimpleFileVisitor<Path>...` does not follow symlink directory. 
  * Proposed change follow symbolic directory if `follow_symlinks` set `true` by default.

## `follow_symlink`: `true` or `false` by default

* I think It is better to set `follow_symlinks` true by default.

Let's consider the following scenario.

```
link_sample
|-- csv
|   `-- sample_01.csv.gz
|-- csv_link -> csv
`-- seed.yml
```

```yaml
in:
  type: file
#  path_prefix: /private/tmp/link_sample/csv/sample_
  path_prefix: /private/tmp/link_sample/csv_link/sample_
  follow_symlinks: false
  decoders:
  - {type: gzip}
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
out: {type: stdout}
```

If `follow_symlink` is `false` by default, the result is `no input data`.

```
2017-04-03 18:59:17.246 +0900 [INFO] (0001:transaction): Listing local files at directory '/private/tmp/link_sample/csv_link' filtering filename by prefix 'sample_'
2017-04-03 18:59:17.251 +0900 [INFO] (0001:transaction): Loading files []
2017-04-03 18:59:17.314 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / tasks=0
2017-04-03 18:59:17.325 +0900 [INFO] (main): Committed.
2017-04-03 18:59:17.325 +0900 [INFO] (main): Next config diff: {"in":{},"out":{}}
```

I think users expect that the Embulk will read `csv_link/sample_01.csv.gz`. 

Additionally, the latest version(v0.8.18) raise an exception if input data is a symbolic directory. 
For this reason, there are no users to use the symbolic link which points to a directory at this time.

## Conclusion.

This PR fix and change the following behavior. 

* Avoid an exception and traverse the directory if a symbolic link points to a directory. 
* Add `follow_symlinks` option for disable traverse symbolic directory if `follow_symlinks` set to `false`.

**Comment by dmikurube** [comment]
@hiroyuki-sato Sorry, I don't get your points yet... Can you summarize facts **in short** :

* What is the problem to solve.
* How the existing implementation works.
* How your proposed `follow_symlinks == true` works.
* How your proposed `follow_symlinks == false` works.

**Comment by hiroyuki-sato** [comment]
@dmikurube Thank you for the comment.

I describe simply about this PR. 

> * What is the problem to solve.
* Avoid raising an exception if a symbolic link points to a directory.
* Add `follow_symlinks` options.
> * How the existing implementation works.
* If a symbolic link points to a directory, the latest version (v0.8.18) throws FileNotFoundException, The Embulk stops and then any data are not ingested 
* If a symbolic link points to a file, ingested it.
> * How your proposed follow_symlinks == true works.
* Traverse directory if a symbolic link file point to a directory. 
* If a symbolic link points to a file, ingested it(no change current behavior). 
* This is the default behavior in this PR.
> * How your proposed follow_symlinks == false works.
* Don't traverse directory if a symbolic link file point to a directory. 
* If a symbolic link points to a file, ingested it(no change current behavior).

File: embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java [hunk 7]
```diff
@@ -148,6 +165,16 @@ public FileVisitResult preVisitDirectory(Path path, BasicFileAttributes attrs)
                 @Override
                 public FileVisitResult visitFile(Path path, BasicFileAttributes attrs)
                 {
+                    try {
```
Comment (dmikurube) [inline embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java]: The actual goal of this part looks avoiding directories from listing, even if they are symbolic links or not. Not checking whether they are symbolic links. Right?

How about making this comment like:

```
// Avoid directories from listing.
// Directories are normally unvisited with |FileVisitor#visitFile|, but symbolic links to
// directories are visited like files unless |FOLLOW_LINKS| is set in |Files#walkFileTree|.
// Symbolic links to directories are explicitly skipped here by checking with |Path#toReadlPath|.
```

File: embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java [hunk 8]
```diff
@@ -148,6 +165,16 @@ public FileVisitResult preVisitDirectory(Path path, BasicFileAttributes attrs)
...
+                        // Check symbolic file which points to a directory.
+                        // This part is called if the option `follow_symlinks` false.
+                        // If the real path is a directory, just ignore it.
+                        if(Files.isDirectory(path.toRealPath())) {
```
Comment (dmikurube) [inline embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java]: nit: space after `if`

File: embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java [hunk 9]
```diff
@@ -148,6 +165,16 @@ public FileVisitResult preVisitDirectory(Path path, BasicFileAttributes attrs)
...
+                            return FileVisitResult.CONTINUE;
+                        }
+                    } catch (IOException ex){
+                        throw new RuntimeException("Can't resolve symbolic link",ex);
```
Comment (dmikurube) [inline embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java]: nit: space after `,`

File: embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java [hunk 10]
```diff
@@ -120,7 +128,16 @@ public void cleanup(TaskSource taskSource,
         final String lastPath = task.getLastPath().orNull();
         try {
             log.info("Listing local files at directory '{}' filtering filename by prefix '{}'", directory.equals(CURRENT_DIR) ? "." : directory.toString(), fileNamePrefix);
-            Files.walkFileTree(directory, new SimpleFileVisitor<Path>() {
+
+            int maxDepth = Integer.MAX_VALUE;
+            Set<FileVisitOption> opts;
+            if( task.getFollowSymlinks() ) {
```
Comment (dmikurube) [inline embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java]: nit: space after `if`, and remove space after `(` and before `)`

Comment (hiroyuki-sato) [inline embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java]: Thanks. fixed.

File: embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java (hunk 7 above)
Comment (hiroyuki-sato) [inline embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java]: I copied your comment as is.

File: embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java (hunk 8 above)
Comment (hiroyuki-sato) [inline embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java]: Added space.

File: embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java (hunk 9 above)
Comment (hiroyuki-sato) [inline embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java]: Added space.

**Comment by hiroyuki-sato** [comment]
@dmikurube 
It's hard to write test codes for me. I have no idea how to write it for symbolic links. 
Can you write sample code for me?

By the way, I add the following message. It may helpful for users.

```
2017-04-04 09:22:40.673 +0900 [INFO] (0001:transaction): The option `follow_symlinks` set to `false`. Disable visit symbolic links to directories.
```

File: embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java [hunk 11]
```diff
@@ -131,10 +131,11 @@ public void cleanup(TaskSource taskSource,
 
             int maxDepth = Integer.MAX_VALUE;
             Set<FileVisitOption> opts;
-            if( task.getFollowSymlinks() ) {
+            if(task.getFollowSymlinks()) {
                 opts = EnumSet.of(FileVisitOption.FOLLOW_LINKS);
             } else {
                 opts = EnumSet.noneOf(FileVisitOption.class);
+                log.info("The option `follow_symlinks` set to `false`. Disable visit symbolic links to directories.");
```
Comment (dmikurube) [inline embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java]: How about:

```
"follow_symlinks" is set false. Note that symbolic links to directories are skipped.
```

File: embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java [hunk 12]
```diff
@@ -131,10 +131,11 @@ public void cleanup(TaskSource taskSource,
 
             int maxDepth = Integer.MAX_VALUE;
             Set<FileVisitOption> opts;
-            if( task.getFollowSymlinks() ) {
+            if(task.getFollowSymlinks()) {
```
Comment (dmikurube) [inline embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java]: really style nit: if we accept the fix below, add a space just after `if` in passing.

File: embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java (hunk 11 above)
Comment (hiroyuki-sato) [inline embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java]: I copied the statement as is.

**Comment by muga** [comment]
> @muga From those behaviors described in #585 (comment), follow_symlinks == false seems better as default because the behavior does not change in terms of that "files under symlink'ed directories are finally not ingested". Wdyt?

Sorry for taking so long to reply. The change looks good to me. I merge this after I confirm that the change works expectedly on my local.

**Comment by muga** [comment]
@hiroyuki-sato I created PR for your original branch. Please take a look.

**Comment by hiroyuki-sato** [comment]
@muga Merged! Thank you.

Both `follow_symlinks` `true` and `false`,
it ingested a symbolic link which points to a **file**. 

How do you think this sentence in the built-in manual?

```
If `true`, follow symbolic links
```

Is it better the following?

```
If `true`, follow symbolic link directories
```

**Comment by muga** [comment]
@hiroyuki-sato sounds good. can you fix it?

**Comment by hiroyuki-sato** [comment]
@muga Thank you for reviewing. 
I fixed the built-in document.

**Comment by muga** [comment]
@hiroyuki-sato Thank you. I will merge this PR once the CI passed. cc: @dmikurube

**Comment by hiroyuki-sato** [comment]
Thank you!
