### PR TITLE
Load/require 'jruby' explicitly in JRuby 9.3+ (Fix #1501)

### LINKED ISSUE #1501: Embulk 0.10.35 with JRuby 9.3.3.0 raise the NoMethodError with "undefined method `runtime'"
Issue Type: Bug Report
-----------------------

* Write the following environmental information.
  * OS version: macOS 12.3.1
  * Java version: 1.8.0_291
  * Embulk version: 0.10.35
  * Your Embulk configuration (YAML)
  * Plugin versions
    * embulk-input-postgresql: 0.12.3
* Write all what you did, e.g. your commands executed
* Write what you expected and observed actually

Embulk 0.10.35 with JRuby 9.3.3.0 raise the following exception when a java plugin load.

```
org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `runtime' for JRuby:Module
```

It relates to [this issue](https://github.com/msgpack/msgpack-ruby/issues/226).

```
cat ~/.embulk-dev/embulk.properties
jruby=file:///Users/user/.embulk/jars/jruby-complete-9.3.3.0.jar
```

```
java -jar ~/.embulk/bin/embulk-0.10.x -X embulk_home=$HOME/.embulk-dev run conf.yml
2022-04-15 21:17:07.288 +0900 [INFO] (main): embulk_home is set from command-line: /Users/user/.embulk-dev
2022-04-15 21:17:07.291 +0900 [INFO] (main): m2_repo is set as a sub directory of embulk_home: /Users/user/.embulk-dev/lib/m2/repository
2022-04-15 21:17:07.292 +0900 [INFO] (main): gem_home is set as a sub directory of embulk_home: /Users/user/.embulk-dev/lib/gems
2022-04-15 21:17:07.292 +0900 [INFO] (main): gem_path is set empty.
2022-04-15 21:17:07.630 +0900 [INFO] (main): Started Embulk v0.10.35
2022-04-15 21:17:11.357 +0900 [INFO] (0001:transaction): Gem's home and path are set by system configs "gem_home": "/Users/user/.embulk-dev/lib/gems", "gem_path": ""
org.embulk.config.ConfigException: InputPlugin 'postgresql' is not found.
Maven repository specified is not found at "/Users/user/.embulk-dev/lib/m2/repository" ("/Users/user/.embulk-dev/lib/m2/repository").
org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `runtime' for JRuby:Module
	at org.embulk.plugin.PluginManager.buildPluginNotFoundException(PluginManager.java:155)
	at org.embulk.plugin.PluginManager.newPlugin(PluginManager.java:99)
	at org.embulk.spi.ExecSessionInternal.newPlugin(ExecSessionInternal.java:358)
	at org.embulk.spi.ExecInternal.newPlugin(ExecInternal.java:50)
	at org.embulk.exec.BulkLoader$ProcessPluginSet.<init>(BulkLoader.java:440)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:515)
	at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:352)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:349)
	at org.embulk.spi.ExecInternal.doWith(ExecInternal.java:26)
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:349)
	at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:278)
	at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:288)
	at org.embulk.EmbulkRunner.run(EmbulkRunner.java:153)
	at org.embulk.cli.EmbulkRun.runInternal(EmbulkRun.java:118)
	at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:24)
	at org.embulk.cli.Main.main(Main.java:55)
	Suppressed: org.embulk.plugin.PluginSourceNotMatchException
		at org.embulk.plugin.BuiltinPluginSource.newPlugin(BuiltinPluginSource.java:244)
		at org.embulk.plugin.PluginManager.newPlugin(PluginManager.java:76)
		... 15 more
	Suppressed: org.embulk.plugin.PluginSourceNotMatchException: org.embulk.deps.maven.MavenRepositoryNotFoundException: Maven repository specified is not found at "/Users/user/.embulk-dev/lib/m2/repository" ("/Users/user/.embulk-dev/lib/m2/repository").
		at org.embulk.plugin.maven.MavenPluginRegistry.findPluginPaths(MavenPluginRegistry.java:102)
		at org.embulk.plugin.maven.MavenPluginRegistry.lookup(MavenPluginRegistry.java:71)
		at org.embulk.plugin.maven.MavenPluginSource.newPlugin(MavenPluginSource.java:33)
		at org.embulk.plugin.PluginManager.newPlugin(PluginManager.java:82)
		... 15 more
	Caused by: org.embulk.deps.maven.MavenRepositoryNotFoundException: Maven repository specified is not found at "/Users/user/.embulk-dev/lib/m2/repository" ("/Users/user/.embulk-dev/lib/m2/repository").
		at org.embulk.deps.maven.MavenArtifactFinderImpl.<init>(MavenArtifactFinderImpl.java:44)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at org.embulk.deps.maven.MavenArtifactFinder.create(MavenArtifactFinder.java:13)
		at org.embulk.plugin.maven.MavenPluginRegistry.findPluginPaths(MavenPluginRegistry.java:100)
		... 18 more
	Caused by: java.nio.file.NoSuchFileException: /Users/user/.embulk-dev/lib/m2/repository
		... 25 more
	Suppressed: org.embulk.plugin.PluginSourceNotMatchException
		at org.embulk.plugin.SelfContainedPluginRegistry.search(SelfContainedPluginRegistry.java:77)
		at org.embulk.plugin.SelfContainedPluginRegistry.lookup(SelfContainedPluginRegistry.java:64)
		at org.embulk.plugin.SelfContainedPluginSource.newPlugin(SelfContainedPluginSource.java:44)
		at org.embulk.plugin.PluginManager.newPlugin(PluginManager.java:88)
		... 15 more
	Suppressed: org.embulk.plugin.PluginSourceNotMatchException: Failed to initialize embulk-input-postgresql.
		at org.embulk.jruby.JRubyPluginSource.newPlugin(JRubyPluginSource.java:89)
		at org.embulk.plugin.PluginManager.newPlugin(PluginManager.java:94)
		... 15 more
	Caused by: org.jruby.embed.InvokeFailedException: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `runtime' for JRuby:Module
		at org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.doInvokeMethod(EmbedRubyObjectAdapterImpl.java:253)
		at org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.callMethod(EmbedRubyObjectAdapterImpl.java:158)
		at org.jruby.embed.ScriptingContainer.callMethod(ScriptingContainer.java:1448)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.embulk.jruby.ScriptingContainerDelegateImpl.callMethod(ScriptingContainerDelegateImpl.java:634)
		at org.embulk.jruby.LazyScriptingContainerDelegate.callMethod(LazyScriptingContainerDelegate.java:227)
		at org.embulk.jruby.JRubyPluginSource.newPlugin(JRubyPluginSource.java:87)
		... 16 more
	Caused by: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `runtime' for JRuby:Module
		at RUBY.classloader(/Users/user/.embulk-dev/lib/gems/gems/embulk-0.10.35-java/lib/embulk/java_plugin.rb:18)
		at RUBY.register_input(/Users/user/.embulk-dev/lib/gems/gems/embulk-0.10.35-java/lib/embulk/java_plugin.rb:22)
		at RUBY.<main>(/Users/user/.embulk-dev/lib/gems/gems/embulk-input-postgresql-0.12.3-java/lib/embulk/input/postgresql.rb:1)
		at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1017)
		at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:160)
		at RUBY.require_and_show(/Users/user/.embulk-dev/lib/gems/gems/embulk-0.10.35-java/lib/embulk/plugin_registry.rb:81)
		at RUBY.search(/Users/user/.embulk-dev/lib/gems/gems/embulk-0.10.35-java/lib/embulk/plugin_registry.rb:39)
		at RUBY.lookup(/Users/user/.embulk-dev/lib/gems/gems/embulk-0.10.35-java/lib/embulk/plugin_registry.rb:26)
		at RUBY.lookup(/Users/user/.embulk-dev/lib/gems/gems/embulk-0.10.35-java/lib/embulk/plugin.rb:197)
		at RUBY.new_java_input(/Users/user/.embulk-dev/lib/gems/gems/embulk-0.10.35-java/lib/embulk/plugin.rb:155)
		at RUBY.new_java_input(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/forwardable.rb:230)

Error: InputPlugin 'postgresql' is not found.
Maven repository specified is not found at "/Users/user/.embulk-dev/lib/m2/repository" ("/Users/user/.embulk-dev/lib/m2/repository").
org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `runtime' for JRuby:Module
```

```yaml
in:
  type: postgresql
  host: localhost
  user: user
  password: password
  database: embulk_test
  table: sample
out:
  type: stdout
```

```
embulk_test=# select * from sample;
 id | col_text | col_double |        col_time
----+----------+------------+------------------------
  1 | text     |      1.234 | 2017-04-12 00:00:00+09
(1 row)
```

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
This PR fixes #1501.

JRuby 9.3.0.0 `require 'jruby'` statement for plugin initialization.

This change doesn't change the current behavior.

#### test config

```
embulk_test=# select * from inc_test;
 id | name
----+-------
  1 | apple
(1 row)
```

```yaml
in:
  type: postgresql
  host: localhost
  user: user
  password: password
  database: embulk_test
  table: inc_test
out:
  type: stdout
```

#### with JRuby 9.1.15.0

```
% ./exe/multi-embulk -j 9.1.15.0 -e 0.10.36-SNAPSHOT run /tmp/test.yml
#####################################################
#
# Embulk: /path/to/embulk/embulk/embulk-0.10.36-SNAPSHOT.jar
# JRuby: /path/to/embulk/jruby/jruby-complete-9.1.15.0.jar
# EmbulkHome: /path/to/embulk/embulk_0.10.36-SNAPSHOT_jruby_9.1.15.0
# CMD: run /tmp/test.yml
#
#####################################################
2022-04-22 21:14:23.514 +0900 [INFO] (main): embulk_home is set from command-line: /path/to/embulk/embulk_0.10.36-SNAPSHOT_jruby_9.1.15.0
2022-04-22 21:14:23.518 +0900 [INFO] (main): m2_repo is set as a sub directory of embulk_home: /path/to/embulk/embulk_0.10.36-SNAPSHOT_jruby_9.1.15.0/lib/m2/repository
2022-04-22 21:14:23.518 +0900 [INFO] (main): gem_home is set as a sub directory of embulk_home: /path/to/embulk/embulk_0.10.36-SNAPSHOT_jruby_9.1.15.0/lib/gems
2022-04-22 21:14:23.518 +0900 [INFO] (main): gem_path is set empty.
2022-04-22 21:14:23.876 +0900 [INFO] (main): Started Embulk v0.10.36-SNAPSHOT
2022-04-22 21:14:27.100 +0900 [INFO] (0001:transaction): Gem's home and path are set by system configs "gem_home": "/path/to/embulk/embulk_0.10.36-SNAPSHOT_jruby_9.1.15.0/lib/gems", "gem_path": ""
2022-04-22 21:14:28.311 +0900 [INFO] (0001:transaction): Loaded plugin embulk-input-postgresql (0.12.3)
2022-04-22 21:14:28.580 +0900 [INFO] (0001:transaction): Loaded plugin embulk-output-stdout
2022-04-22 21:14:28.831 +0900 [WARN] (0001:transaction): "UTC" is recognized as "Z" to be compatible with the legacy style.
2022-04-22 21:14:28.879 +0900 [INFO] (0001:transaction): JDBC Driver = /path/to/embulk/embulk_0.10.36-SNAPSHOT_jruby_9.1.15.0/lib/gems/gems/embulk-input-postgresql-0.12.3-java/default_jdbc_driver/postgresql-9.4-1205-jdbc41.jar
2022-04-22 21:14:28.896 +0900 [INFO] (0001:transaction): Connecting to jdbc:postgresql://localhost:5432/embulk_test options {ApplicationName=embulk-input-postgresql, user=user, password=***, tcpKeepAlive=true, loginTimeout=300, socketTimeout=1800}
2022-04-22 21:14:28.976 +0900 [INFO] (0001:transaction): SQL: SET search_path TO "public"
2022-04-22 21:14:28.987 +0900 [INFO] (0001:transaction): Using JDBC Driver PostgreSQL 9.4 JDBC4.1 (build 1205)
2022-04-22 21:14:29.058 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / output tasks 4 = input tasks 1 * 4
2022-04-22 21:14:29.105 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2022-04-22 21:14:29.157 +0900 [WARN] (0014:task-0000): Z is deprecated as a military time zone name. Use UTC instead.
2022-04-22 21:14:29.157 +0900 [WARN] (0014:task-0000): "Z" is recognized as "Z" to be compatible with the legacy style.
2022-04-22 21:14:29.227 +0900 [INFO] (0014:task-0000): Connecting to jdbc:postgresql://localhost:5432/embulk_test options {ApplicationName=embulk-input-postgresql, user=user, password=***, tcpKeepAlive=true, loginTimeout=300, socketTimeout=1800}
2022-04-22 21:14:29.238 +0900 [INFO] (0014:task-0000): SQL: SET search_path TO "public"
2022-04-22 21:14:29.247 +0900 [INFO] (0014:task-0000): SQL: DECLARE cur NO SCROLL CURSOR FOR SELECT * FROM "inc_test"
2022-04-22 21:14:29.249 +0900 [INFO] (0014:task-0000): SQL: FETCH FORWARD 10000 FROM cur
2022-04-22 21:14:29.252 +0900 [INFO] (0014:task-0000): > 0.00 seconds
2022-04-22 21:14:29.259 +0900 [INFO] (0014:task-0000): SQL: FETCH FORWARD 10000 FROM cur
2022-04-22 21:14:29.262 +0900 [INFO] (0014:task-0000): > 0.00 seconds
1,apple
2022-04-22 21:14:29.272 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2022-04-22 21:14:29.280 +0900 [INFO] (main): Committed.
2022-04-22 21:14:29.280 +0900 [INFO] (main): Next config diff: {"in":{},"out":{}}
```

#### with JRuby 9.2.20.1

```
% ./exe/multi-embulk -j 9.2.20.1 -e 0.10.36-SNAPSHOT run /tmp/test.yml
#####################################################
#
# Embulk: /path/to/embulk/embulk/embulk-0.10.36-SNAPSHOT.jar
# JRuby: /path/to/embulk/jruby/jruby-complete-9.2.20.1.jar
# EmbulkHome: /path/to/embulk/embulk_0.10.36-SNAPSHOT_jruby_9.2.20.1
# CMD: run /tmp/test.yml
#
#####################################################
2022-04-22 21:14:38.387 +0900 [INFO] (main): embulk_home is set from command-line: /path/to/embulk/embulk_0.10.36-SNAPSHOT_jruby_9.2.20.1
2022-04-22 21:14:38.391 +0900 [INFO] (main): m2_repo is set as a sub directory of embulk_home: /path/to/embulk/embulk_0.10.36-SNAPSHOT_jruby_9.2.20.1/lib/m2/repository
2022-04-22 21:14:38.391 +0900 [INFO] (main): gem_home is set as a sub directory of embulk_home: /path/to/embulk/embulk_0.10.36-SNAPSHOT_jruby_9.2.20.1/lib/gems
2022-04-22 21:14:38.391 +0900 [INFO] (main): gem_path is set empty.
2022-04-22 21:14:38.761 +0900 [INFO] (main): Started Embulk v0.10.36-SNAPSHOT
2022-04-22 21:14:42.234 +0900 [INFO] (0001:transaction): Gem's home and path are set by system configs "gem_home": "/path/to/embulk/embulk_0.10.36-SNAPSHOT_jruby_9.2.20.1/lib/gems", "gem_path": ""
2022-04-22 21:14:43.116 +0900 [INFO] (0001:transaction): Loaded plugin embulk-input-postgresql (0.12.3)
2022-04-22 21:14:43.351 +0900 [INFO] (0001:transaction): Loaded plugin embulk-output-stdout
2022-04-22 21:14:43.573 +0900 [WARN] (0001:transaction): "UTC" is recognized as "Z" to be compatible with the legacy style.
2022-04-22 21:14:43.614 +0900 [INFO] (0001:transaction): JDBC Driver = /path/to/embulk/embulk_0.10.36-SNAPSHOT_jruby_9.2.20.1/lib/gems/gems/embulk-input-postgresql-0.12.3-java/default_jdbc_driver/postgresql-9.4-1205-jdbc41.jar
2022-04-22 21:14:43.626 +0900 [INFO] (0001:transaction): Connecting to jdbc:postgresql://localhost:5432/embulk_test options {ApplicationName=embulk-input-postgresql, user=user, password=***, tcpKeepAlive=true, loginTimeout=300, socketTimeout=1800}
2022-04-22 21:14:43.748 +0900 [INFO] (0001:transaction): SQL: SET search_path TO "public"
2022-04-22 21:14:43.765 +0900 [INFO] (0001:transaction): Using JDBC Driver PostgreSQL 9.4 JDBC4.1 (build 1205)
2022-04-22 21:14:43.862 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / output tasks 4 = input tasks 1 * 4
2022-04-22 21:14:43.922 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2022-04-22 21:14:43.980 +0900 [WARN] (0014:task-0000): Z is deprecated as a military time zone name. Use UTC instead.
2022-04-22 21:14:43.980 +0900 [WARN] (0014:task-0000): "Z" is recognized as "Z" to be compatible with the legacy style.
2022-04-22 21:14:44.050 +0900 [INFO] (0014:task-0000): Connecting to jdbc:postgresql://localhost:5432/embulk_test options {ApplicationName=embulk-input-postgresql, user=user, password=***, tcpKeepAlive=true, loginTimeout=300, socketTimeout=1800}
2022-04-22 21:14:44.062 +0900 [INFO] (0014:task-0000): SQL: SET search_path TO "public"
2022-04-22 21:14:44.070 +0900 [INFO] (0014:task-0000): SQL: DECLARE cur NO SCROLL CURSOR FOR SELECT * FROM "inc_test"
2022-04-22 21:14:44.080 +0900 [INFO] (0014:task-0000): SQL: FETCH FORWARD 10000 FROM cur
2022-04-22 21:14:44.083 +0900 [INFO] (0014:task-0000): > 0.00 seconds
2022-04-22 21:14:44.087 +0900 [INFO] (0014:task-0000): SQL: FETCH FORWARD 10000 FROM cur
2022-04-22 21:14:44.095 +0900 [INFO] (0014:task-0000): > 0.01 seconds
1,apple
2022-04-22 21:14:44.103 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2022-04-22 21:14:44.118 +0900 [INFO] (main): Committed.
2022-04-22 21:14:44.118 +0900 [INFO] (main): Next config diff: {"in":{},"out":{}}
```

#### with JRuby 9.3.4.0

```
% ./exe/multi-embulk -j 9.3.4.0 -e 0.10.36-SNAPSHOT run /tmp/test.yml
#####################################################
#
# Embulk: /path/to/embulk/embulk/embulk-0.10.36-SNAPSHOT.jar
# JRuby: /path/to/embulk/jruby/jruby-complete-9.3.4.0.jar
# EmbulkHome: /path/to/embulk/embulk_0.10.36-SNAPSHOT_jruby_9.3.4.0
# CMD: run /tmp/test.yml
#
#####################################################
2022-04-22 21:14:58.488 +0900 [INFO] (main): embulk_home is set from command-line: /path/to/embulk/embulk_0.10.36-SNAPSHOT_jruby_9.3.4.0
2022-04-22 21:14:58.491 +0900 [INFO] (main): m2_repo is set as a sub directory of embulk_home: /path/to/embulk/embulk_0.10.36-SNAPSHOT_jruby_9.3.4.0/lib/m2/repository
2022-04-22 21:14:58.491 +0900 [INFO] (main): gem_home is set as a sub directory of embulk_home: /path/to/embulk/embulk_0.10.36-SNAPSHOT_jruby_9.3.4.0/lib/gems
2022-04-22 21:14:58.492 +0900 [INFO] (main): gem_path is set empty.
2022-04-22 21:14:58.880 +0900 [INFO] (main): Started Embulk v0.10.36-SNAPSHOT
2022-04-22 21:15:03.079 +0900 [INFO] (0001:transaction): Gem's home and path are set by system configs "gem_home": "/path/to/embulk/embulk_0.10.36-SNAPSHOT_jruby_9.3.4.0/lib/gems", "gem_path": ""
2022-04-22 21:15:04.321 +0900 [INFO] (0001:transaction): Loaded plugin embulk-input-postgresql (0.12.3)
2022-04-22 21:15:04.581 +0900 [INFO] (0001:transaction): Loaded plugin embulk-output-stdout
2022-04-22 21:15:04.819 +0900 [WARN] (0001:transaction): "UTC" is recognized as "Z" to be compatible with the legacy style.
2022-04-22 21:15:04.868 +0900 [INFO] (0001:transaction): JDBC Driver = /path/to/embulk/embulk_0.10.36-SNAPSHOT_jruby_9.3.4.0/lib/gems/gems/embulk-input-postgresql-0.12.3-java/default_jdbc_driver/postgresql-9.4-1205-jdbc41.jar
2022-04-22 21:15:04.890 +0900 [INFO] (0001:transaction): Connecting to jdbc:postgresql://localhost:5432/embulk_test options {ApplicationName=embulk-input-postgresql, user=user, password=***, tcpKeepAlive=true, loginTimeout=300, socketTimeout=1800}
2022-04-22 21:15:05.012 +0900 [INFO] (0001:transaction): SQL: SET search_path TO "public"
2022-04-22 21:15:05.028 +0900 [INFO] (0001:transaction): Using JDBC Driver PostgreSQL 9.4 JDBC4.1 (build 1205)
2022-04-22 21:15:05.157 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / output tasks 4 = input tasks 1 * 4
2022-04-22 21:15:05.230 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2022-04-22 21:15:05.281 +0900 [WARN] (0014:task-0000): Z is deprecated as a military time zone name. Use UTC instead.
2022-04-22 21:15:05.282 +0900 [WARN] (0014:task-0000): "Z" is recognized as "Z" to be compatible with the legacy style.
2022-04-22 21:15:05.373 +0900 [INFO] (0014:task-0000): Connecting to jdbc:postgresql://localhost:5432/embulk_test options {ApplicationName=embulk-input-postgresql, user=user, password=***, tcpKeepAlive=true, loginTimeout=300, socketTimeout=1800}
2022-04-22 21:15:05.384 +0900 [INFO] (0014:task-0000): SQL: SET search_path TO "public"
2022-04-22 21:15:05.392 +0900 [INFO] (0014:task-0000): SQL: DECLARE cur NO SCROLL CURSOR FOR SELECT * FROM "inc_test"
2022-04-22 21:15:05.396 +0900 [INFO] (0014:task-0000): SQL: FETCH FORWARD 10000 FROM cur
2022-04-22 21:15:05.398 +0900 [INFO] (0014:task-0000): > 0.00 seconds
2022-04-22 21:15:05.402 +0900 [INFO] (0014:task-0000): SQL: FETCH FORWARD 10000 FROM cur
2022-04-22 21:15:05.404 +0900 [INFO] (0014:task-0000): > 0.00 seconds
1,apple
2022-04-22 21:15:05.413 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2022-04-22 21:15:05.426 +0900 [INFO] (main): Committed.
2022-04-22 21:15:05.427 +0900 [INFO] (main): Next config diff: {"in":{},"out":{}}
```

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
#1506 fix CI error in the `windows-latest, :embulk-ruby:check`

File: embulk-ruby/lib/embulk/java_plugin.rb [hunk 1]
```diff
@@ -1,5 +1,6 @@
 module Embulk
 
+  require 'jruby'
```
Comment (dmikurube) [inline embulk-ruby/lib/embulk/java_plugin.rb:3]: Questions:
* How is `require 'jruby'` related to `require 'java'`? Doesn't this conflict with `'java'`?
* Doesn't older JRuby have no problems even with `require 'jruby'`?
* Is it the right place to add this `require 'jruby'`? Why not the same place with `require 'java'`?

Comment (hiroyuki-sato) [reply embulk-ruby/lib/embulk/java_plugin.rb:3]: @dmikurube Thank you for your comment.

> Doesn't older JRuby have no problems even with `require 'jruby'`?

I tested this PR using JRuby 9.1.15.0, 9.2.20.1, and 9.3.4.0 (Please see the log above)
The rest of the two comments will answer later.

Comment (dmikurube) [reply embulk-ruby/lib/embulk/java_plugin.rb:3]: They look to be tested based on Java plugins (even though they are packaged in Gems). JRuby is used only to load Gems there.

Are they really okay with 100% Ruby plugins?

Comment (dmikurube) [reply embulk-ruby/lib/embulk/java_plugin.rb:3]: Especially in maintaining JRuby-related things in Embulk, I'm negative to make changes by "Tested, worked, then let's go with it."  We've often faced unexpected breakage by such changes.

We wanted to understand :
* What is the background in JRuby.
* How that part is implemented inside JRuby version-to-version.

**Comment by hiroyuki-sato** [comment]
@dmikurube What do you think about this background description?

This statement is necessary for using `JRuby.runtime` method from JRuby 9.3.0.0.
JRuby.runtime happened to work without `require jruby` < 9.3, because it was implemented by the Java core feature. This implementation has been changed in JRuby 9.3.0.0.

https://github.com/jruby/jruby/issues/7221#issuecomment-1133646241

I'll add some tests result later, but I believe this change doesn't change the current behavior.
Because load ruby module only >= 9.3

File: embulk-ruby/lib/embulk/java/imports.rb [hunk 2]
```diff
@@ -1,4 +1,14 @@
...
+#
+# This statement is necessary for using JRuby.runtime method from JRuby 9.3.0.0.
+# JRuby.runtime happened to work without `require jruby` < 9.3,
+# because it was implemented by Java core feature.
+# This implementation has been changed in JRuby 9.3.0.0.
+#
+# See also.
+# https://github.com/jruby/jruby/issues/7221#issuecomment-1133646241
+#
+require 'jruby' if JRUBY_VERSION.to_f >= 9.3
```
Comment (dmikurube) [inline embulk-ruby/lib/embulk/java/imports.rb:11]: Reading the comment in `jruby/jruby`, how about the following?

At the same time, `to_f >= 9.3` does not seem safe to me.

```suggestion
# Required to use "Java features" from the Ruby side.
require 'java'

# Required to access JRuby-specific internal features, such as `JRuby.runtime`.
require 'jruby' if Gem::Version.new(JRUBY_VERSION) >= Gem::Version.new('9.3')

# Both of 'java' and 'jruby' should be loaded in Embulk's use-case in nature.
#
# Embulk had loaded only 'java' explicitly until Embulk v0.10.35.
# It was because loading 'java' automatically loaded also 'jruby' until JRuby 9.2.
# But, it has changed since JRuby 9.3. JRuby 9.3+ needs loading 'jruby' explicitly.
#
# See also: https://github.com/jruby/jruby/issues/7221#issuecomment-1133646241
#
# Here, Embulk limits loading 'jruby' only in JRuby 9.3+ to ensure compatibility.
# We may remove the limitation in the future.
```

**Review by dmikurube — COMMENTED** [review]
1: Could you squash and rebase the commits?

2: Could you update the commit message and the Pull Request subject to :
```
Load/require 'jruby' explicitly in JRuby 9.3+ (Fix #1501)
```

**Comment by hiroyuki-sato** [comment]
@dmikurube Thank you for your review. I rebase and update the commit message and PR subject.
I also added the `Co-authored-by` part.

**Comment by dmikurube** [comment]
Thanks for accepting the suggestion! When you have time, can you check it again in the same test settings? (It would need some more time to merge this and release v0.10.36.)

**Comment by hiroyuki-sato** [comment]
Hello, @dmikurube. Thank you for your comment. It worked well.



#### with JRuby 9.3.4.0


```
％ ./exe/multi-embulk -e 0.10.36-SNAPSHOT -j 9.3.4.0 run /tmp/test.yml
#####################################################
#
# Embulk: /path/to/embulk-dev-helpers/build/embulk/embulk-0.10.36-SNAPSHOT.jar
# JRuby: /path/to/embulk-dev-helpers/build/jruby/jruby-complete-9.3.4.0.jar
# EmbulkHome: /path/to/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.3.4.0
# CMD: run /tmp/test.yml
#
#####################################################
2022-06-08 15:34:33.238 +0900 [INFO] (main): embulk_home is set from command-line: /path/to/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.3.4.0
2022-06-08 15:34:33.241 +0900 [INFO] (main): m2_repo is set as a sub directory of embulk_home: /path/to/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.3.4.0/lib/m2/repository
2022-06-08 15:34:33.242 +0900 [INFO] (main): gem_home is set as a sub directory of embulk_home: /path/to/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.3.4.0/lib/gems
2022-06-08 15:34:33.242 +0900 [INFO] (main): gem_path is set empty.
2022-06-08 15:34:33.593 +0900 [INFO] (main): Started Embulk v0.10.36-SNAPSHOT
2022-06-08 15:34:37.390 +0900 [INFO] (0001:transaction): Gem's home and path are set by system configs "gem_home":  /path/to/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.3.4.0/lib/gems", "gem_path": ""
2022-06-08 15:34:38.879 +0900 [INFO] (0001:transaction): Loaded plugin embulk-input-postgresql (0.12.4)
2022-06-08 15:34:39.165 +0900 [INFO] (0001:transaction): Loaded plugin embulk-output-stdout
2022-06-08 15:34:39.425 +0900 [WARN] (0001:transaction): "UTC" is recognized as "Z" to be compatible with the legacy style.
2022-06-08 15:34:39.436 +0900 [INFO] (0001:transaction): JDBC Driver = /path/to/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.3.4.0/lib/gems/gems/embulk-input-postgresql-0.12.4-java/default_jdbc_driver/postgresql-9.4-1205-jdbc41.jar
2022-06-08 15:34:39.447 +0900 [INFO] (0001:transaction): Connecting to jdbc:postgresql://localhost:5432/embulk_test options {ApplicationName=embulk-input-postgresql, user=hsato, password=***, tcpKeepAlive=true, loginTimeout=300, socketTimeout=1800}
2022-06-08 15:34:39.569 +0900 [INFO] (0001:transaction): SQL: SET search_path TO "public"
2022-06-08 15:34:39.593 +0900 [INFO] (0001:transaction): Using JDBC Driver PostgreSQL 9.4 JDBC4.1 (build 1205)
2022-06-08 15:34:39.687 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / output tasks 4 = input tasks 1 * 4
2022-06-08 15:34:39.746 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2022-06-08 15:34:39.815 +0900 [WARN] (0014:task-0000): Z is deprecated as a military time zone name. Use UTC instead.
2022-06-08 15:34:39.815 +0900 [WARN] (0014:task-0000): "Z" is recognized as "Z" to be compatible with the legacy style.
2022-06-08 15:34:39.903 +0900 [INFO] (0014:task-0000): Connecting to jdbc:postgresql://localhost:5432/embulk_test options {ApplicationName=embulk-input-postgresql, user=hsato, password=***, tcpKeepAlive=true, loginTimeout=300, socketTimeout=1800}
2022-06-08 15:34:39.946 +0900 [INFO] (0014:task-0000): SQL: SET search_path TO "public"
2022-06-08 15:34:39.951 +0900 [INFO] (0014:task-0000): SQL: DECLARE cur NO SCROLL CURSOR FOR SELECT * FROM "inc_test"
2022-06-08 15:34:39.956 +0900 [INFO] (0014:task-0000): SQL: FETCH FORWARD 10000 FROM cur
2022-06-08 15:34:39.960 +0900 [INFO] (0014:task-0000): > 0.00 seconds
2022-06-08 15:34:39.965 +0900 [INFO] (0014:task-0000): SQL: FETCH FORWARD 10000 FROM cur
2022-06-08 15:34:39.968 +0900 [INFO] (0014:task-0000): > 0.00 seconds
1,apple
2022-06-08 15:34:39.981 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2022-06-08 15:34:39.988 +0900 [INFO] (main): Committed.
2022-06-08 15:34:39.988 +0900 [INFO] (main): Next config diff: {"in":{},"out":{}}
```

#### with JRuby 9.2.20.1


```
％ ./exe/multi-embulk -e 0.10.36-SNAPSHOT -j 9.2.20.1 run /tmp/test.yml
#####################################################
#
# Embulk: /path/to/embulk-dev-helpers/build/embulk/embulk-0.10.36-SNAPSHOT.jar
# JRuby: /path/to/embulk-dev-helpers/build/jruby/jruby-complete-9.2.20.1.jar
# EmbulkHome: /path/to/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.2.20.1
# CMD: run /tmp/test.yml
#
#####################################################
2022-06-08 15:34:49.350 +0900 [INFO] (main): embulk_home is set from command-line: /path/to/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.2.20.1
2022-06-08 15:34:49.353 +0900 [INFO] (main): m2_repo is set as a sub directory of embulk_home: /path/to/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.2.20.1/lib/m2/repository
2022-06-08 15:34:49.353 +0900 [INFO] (main): gem_home is set as a sub directory of embulk_home: /path/to/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.2.20.1/lib/gems
2022-06-08 15:34:49.353 +0900 [INFO] (main): gem_path is set empty.
2022-06-08 15:34:49.693 +0900 [INFO] (main): Started Embulk v0.10.36-SNAPSHOT
2022-06-08 15:34:53.152 +0900 [INFO] (0001:transaction): Gem's home and path are set by system configs "gem_home":  /path/to/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.2.20.1/lib/gems", "gem_path": ""
2022-06-08 15:34:54.402 +0900 [INFO] (0001:transaction): Loaded plugin embulk-input-postgresql (0.12.4)
2022-06-08 15:34:54.586 +0900 [INFO] (0001:transaction): Loaded plugin embulk-output-stdout
2022-06-08 15:34:54.776 +0900 [WARN] (0001:transaction): "UTC" is recognized as "Z" to be compatible with the legacy style.
2022-06-08 15:34:54.784 +0900 [INFO] (0001:transaction): JDBC Driver = /path/to/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.2.20.1/lib/gems/gems/embulk-input-postgresql-0.12.4-java/default_jdbc_driver/postgresql-9.4-1205-jdbc41.jar
2022-06-08 15:34:54.789 +0900 [INFO] (0001:transaction): Connecting to jdbc:postgresql://localhost:5432/embulk_test options {ApplicationName=embulk-input-postgresql, user=hsato, password=***, tcpKeepAlive=true, loginTimeout=300, socketTimeout=1800}
2022-06-08 15:34:54.869 +0900 [INFO] (0001:transaction): SQL: SET search_path TO "public"
2022-06-08 15:34:54.881 +0900 [INFO] (0001:transaction): Using JDBC Driver PostgreSQL 9.4 JDBC4.1 (build 1205)
2022-06-08 15:34:54.960 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / output tasks 4 = input tasks 1 * 4
2022-06-08 15:34:55.016 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2022-06-08 15:34:55.067 +0900 [WARN] (0014:task-0000): Z is deprecated as a military time zone name. Use UTC instead.
2022-06-08 15:34:55.067 +0900 [WARN] (0014:task-0000): "Z" is recognized as "Z" to be compatible with the legacy style.
2022-06-08 15:34:55.123 +0900 [INFO] (0014:task-0000): Connecting to jdbc:postgresql://localhost:5432/embulk_test options {ApplicationName=embulk-input-postgresql, user=hsato, password=***, tcpKeepAlive=true, loginTimeout=300, socketTimeout=1800}
2022-06-08 15:34:55.147 +0900 [INFO] (0014:task-0000): SQL: SET search_path TO "public"
2022-06-08 15:34:55.149 +0900 [INFO] (0014:task-0000): SQL: DECLARE cur NO SCROLL CURSOR FOR SELECT * FROM "inc_test"
2022-06-08 15:34:55.152 +0900 [INFO] (0014:task-0000): SQL: FETCH FORWARD 10000 FROM cur
2022-06-08 15:34:55.153 +0900 [INFO] (0014:task-0000): > 0.00 seconds
2022-06-08 15:34:55.157 +0900 [INFO] (0014:task-0000): SQL: FETCH FORWARD 10000 FROM cur
2022-06-08 15:34:55.159 +0900 [INFO] (0014:task-0000): > 0.00 seconds
1,apple
2022-06-08 15:34:55.164 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2022-06-08 15:34:55.175 +0900 [INFO] (main): Committed.
2022-06-08 15:34:55.175 +0900 [INFO] (main): Next config diff: {"in":{},"out":{}}
```

#### with JRuby 9.1.15.0


```
％ ./exe/multi-embulk -e 0.10.36-SNAPSHOT -j 9.1.15.0 run /tmp/test.yml
#####################################################
#
# Embulk: /path/to/embulk-dev-helpers/build/embulk/embulk-0.10.36-SNAPSHOT.jar
# JRuby: /path/to/embulk-dev-helpers/build/jruby/jruby-complete-9.1.15.0.jar
# EmbulkHome: /path/to/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.1.15.0
# CMD: run /tmp/test.yml
#
#####################################################
2022-06-08 15:35:04.205 +0900 [INFO] (main): embulk_home is set from command-line: /path/to/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.1.15.0
2022-06-08 15:35:04.208 +0900 [INFO] (main): m2_repo is set as a sub directory of embulk_home: /path/to/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.1.15.0/lib/m2/repository
2022-06-08 15:35:04.208 +0900 [INFO] (main): gem_home is set as a sub directory of embulk_home: /path/to/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.1.15.0/lib/gems
2022-06-08 15:35:04.208 +0900 [INFO] (main): gem_path is set empty.
2022-06-08 15:35:04.524 +0900 [INFO] (main): Started Embulk v0.10.36-SNAPSHOT
2022-06-08 15:35:07.598 +0900 [INFO] (0001:transaction): Gem's home and path are set by system configs "gem_home":  /path/to/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.1.15.0/lib/gems", "gem_path": ""
2022-06-08 15:35:08.439 +0900 [INFO] (0001:transaction): Loaded plugin embulk-input-postgresql (0.12.4)
2022-06-08 15:35:08.637 +0900 [INFO] (0001:transaction): Loaded plugin embulk-output-stdout
2022-06-08 15:35:08.812 +0900 [WARN] (0001:transaction): "UTC" is recognized as "Z" to be compatible with the legacy style.
2022-06-08 15:35:08.843 +0900 [INFO] (0001:transaction): JDBC Driver = /path/to/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.1.15.0/lib/gems/gems/embulk-input-postgresql-0.12.4-java/default_jdbc_driver/postgresql-9.4-1205-jdbc41.jar
2022-06-08 15:35:08.852 +0900 [INFO] (0001:transaction): Connecting to jdbc:postgresql://localhost:5432/embulk_test options {ApplicationName=embulk-input-postgresql, user=hsato, password=***, tcpKeepAlive=true, loginTimeout=300, socketTimeout=1800}
2022-06-08 15:35:08.941 +0900 [INFO] (0001:transaction): SQL: SET search_path TO "public"
2022-06-08 15:35:08.956 +0900 [INFO] (0001:transaction): Using JDBC Driver PostgreSQL 9.4 JDBC4.1 (build 1205)
2022-06-08 15:35:09.024 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / output tasks 4 = input tasks 1 * 4
2022-06-08 15:35:09.072 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2022-06-08 15:35:09.113 +0900 [WARN] (0014:task-0000): Z is deprecated as a military time zone name. Use UTC instead.
2022-06-08 15:35:09.113 +0900 [WARN] (0014:task-0000): "Z" is recognized as "Z" to be compatible with the legacy style.
2022-06-08 15:35:09.167 +0900 [INFO] (0014:task-0000): Connecting to jdbc:postgresql://localhost:5432/embulk_test options {ApplicationName=embulk-input-postgresql, user=hsato, password=***, tcpKeepAlive=true, loginTimeout=300, socketTimeout=1800}
2022-06-08 15:35:09.194 +0900 [INFO] (0014:task-0000): SQL: SET search_path TO "public"
2022-06-08 15:35:09.197 +0900 [INFO] (0014:task-0000): SQL: DECLARE cur NO SCROLL CURSOR FOR SELECT * FROM "inc_test"
2022-06-08 15:35:09.200 +0900 [INFO] (0014:task-0000): SQL: FETCH FORWARD 10000 FROM cur
2022-06-08 15:35:09.201 +0900 [INFO] (0014:task-0000): > 0.00 seconds
2022-06-08 15:35:09.204 +0900 [INFO] (0014:task-0000): SQL: FETCH FORWARD 10000 FROM cur
2022-06-08 15:35:09.205 +0900 [INFO] (0014:task-0000): > 0.00 seconds
1,apple
2022-06-08 15:35:09.211 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2022-06-08 15:35:09.225 +0900 [INFO] (main): Committed.
2022-06-08 15:35:09.225 +0900 [INFO] (main): Next config diff: {"in":{},"out":{}}
```

**Comment by dmikurube** [comment]
Merging this toward v0.10.36, finally.
