### PR TITLE
Fix the "migrate" subcommand to handle build.gradle correctly

### LINKED ISSUE #699: embulk migrate can't migrate gradle version.
### Expect behavior

I expect that the following command update gradle to 3.X.
Because of this plugin use gradle version 2.12.

```
git clone https://github.com/embulk/embulk-input-jdbc
cd embulk-input-jdbc
embulk migrate .
```

### Actual behavior

```
embulk migrate .
2017-06-28 16:59:06.344 +0900: Embulk v0.8.25
Detected Java plugin for Embulk 0.8.15...
Done. No files are modified.
```

### For fix this issue.

Maybe, GRADLE_VERSION_IN_WRAPPER need to remove extra `/` like the following. 

```diff
diff --git a/embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java b/embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java
index f6c1d9be..734afac8 100644
--- a/embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java
+++ b/embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java
@@ -424,7 +424,7 @@ public class EmbulkMigrate
     private static final Pattern OLD_EMBULK_IN_GEMSPEC = Pattern.compile(
         "embulk-");
     private static final Pattern GRADLE_VERSION_IN_WRAPPER = Pattern.compile(
-        "gradle-[23]\\.\\d+(\\.\\d+)?-/");
+        "gradle-[23]\\.\\d+(\\.\\d+)?-");
     private static final Pattern JSON_COLUMN_METHOD_IN_ALL_JAVA = Pattern.compile(
         "void\\s+jsonColumn");
     private static final Pattern TIMESTAMP_COLUMN_METHOD_IN_ALL_JAVA = Pattern.compile(
```

### Add note

After the fix, I tried `embulk migrate` but I got the following error.

```
embulk migrate .


2017-06-28 16:41:12.129 +0900: Embulk v0.8.25
Detected Java plugin for Embulk 0.8.15...
LoadError: no such file to load -- embulk/command/embulk_main
  require at org/jruby/RubyKernel.java:956
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at file:/path/to/embulk/pkg/embulk-0.8.25.jar!/embulk/command/embulk_bundle.rb:46
```

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
Fix #699 @dmikurube Please take a look when you can.

Un-JRuby embulk migrate replace files properly.

* Fix GRADLE_VERSION_IN_WRAPPER matching pattern.
  * Remove trailing character '/'.
  * The version strings is `gradle-2.12-bin.zip`
* Avoid `FileAlreadyExistsException`.
  * Throw that exception if the file exists.
* Add files into modifiedFiles.
  * For output the following message.
  * `Done. Please check modifieid files.`

By the way, I found typo (not fixed yet this PR)
* modifieid -> modified

### CODE REVIEW

File: embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java [hunk 1]
```diff
@@ -25,6 +25,8 @@
 
 import org.apache.maven.artifact.versioning.ComparableVersion;
 
+import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
```
Comment (dmikurube) [inline embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java]: Please import just `java.nio.file.StandardCopyOption`, and refer like `StandardCopyOption.REPLACE_EXISTING`.

File: embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java [hunk 2]
```diff
@@ -236,7 +238,8 @@ public void copy(String sourceResourcePath, String destinationFileName)
         {
             Path destinationPath = this.basePath.resolve(destinationFileName);
             Files.createDirectories(destinationPath.getParent());
-            Files.copy(EmbulkMigrate.class.getClassLoader().getResourceAsStream(sourceResourcePath), destinationPath);
+            Files.copy(EmbulkMigrate.class.getClassLoader().getResourceAsStream(sourceResourcePath), destinationPath,REPLACE_EXISTING);
```
Comment (dmikurube) [inline embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java]: Add a space or a newline after the comma. (If we use `StandardCopyOption.REPLACE_EXISTING`, a newline could be better.)

File: embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java (hunk 1 above)
Comment (hiroyuki-sato) [inline embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java]: Use `StandardCopyOption.REPLACE_EXISTING` instead of `import static`.

File: embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java (hunk 2 above)
Comment (hiroyuki-sato) [inline embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java]: Add a newline.

**Comment by hiroyuki-sato** [comment]
@dmikurube Thank you for reviewing.

Please take a look again. 

* Fix PR subject.
* Use `StandardCopyOption.REPLACE_EXISTING` instead of static import
* Add newline for long statement.

File: embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java [hunk 3]
```diff
@@ -236,7 +237,9 @@ public void copy(String sourceResourcePath, String destinationFileName)
         {
             Path destinationPath = this.basePath.resolve(destinationFileName);
             Files.createDirectories(destinationPath.getParent());
-            Files.copy(EmbulkMigrate.class.getClassLoader().getResourceAsStream(sourceResourcePath), destinationPath);
+            Files.copy(EmbulkMigrate.class.getClassLoader().getResourceAsStream(sourceResourcePath), destinationPath,
+                    StandardCopyOption.REPLACE_EXISTING);
```
Comment (dmikurube) [inline embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java]: Nicer to align with `(`, but it's okay.

Comment (hiroyuki-sato) [inline embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java]: I don't like this style too. 😄 
Airlift format like that.

Did you mean the following?

```java
Files.copy(EmbulkMigrate.class.getClassLoader().getResourceAsStream(sourceResourcePath), destinationPath,
           StandardCopyOption.REPLACE_EXISTING);
```

Comment (dmikurube) [inline embulk-cli/src/main/java/org/embulk/cli/EmbulkMigrate.java]: Yes, but it's okay. I've merged it for the time being.

I was not sure it was the Airlift format...
