### PR TITLE
Use single super statement (Fix #1513)

### LINKED ISSUE #1513: JRuby 9.3+ raises "Found multiple supers in java ctor" if a plugin does  not found.
Issue Type: Bug Report
-----------------------

* Write the following environmental information.
  * OS version: macOS 12.3.1
  * Java version: 1.8
  * Embulk version: 0.10.36-SNAPSHOT(39d8df31ebb1f19379881d241d38a83f37031a5c) 

JRuby 9.3+ raises "Found multiple supers in java ctor" if a plugin does not found.

```yaml
in:
  type: postgresql2 # no exist plugin.
  host: localhost
  user: user
  password: password
  database: embulk_test
  table: inc_test
out:
  type: stdout
```

JRuby 9.3.4.0

```
Error: InputPlugin 'postgresql2' is not found.
Maven repository specified is not found at "/path/to/embulk/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.3.4.0/lib/m2/repository" ("/path/to/embulk/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.3.4.0/lib/m2/repository").
org.jruby.exceptions.RuntimeError: (RuntimeError) Found multiple supers in java ctor
```

JRuby 9.2.20.1

```
Error: InputPlugin 'postgresql2' is not found.
Maven repository specified is not found at "/path/to/embulk/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.2.20.1/lib/m2/repository" ("/path/to/embulk/embulk-dev-helpers/build/embulk_0.10.36-SNAPSHOT_jruby_9.2.20.1/lib/m2/repository").
org.jruby.proxy.org.embulk.config.ConfigException$Proxy1: Unknown input plugin 'postgresql2'. embulk/input/postgresql2.rb is not installed. Run 'embulk gem search -rd embulk-input' command to find plugins.
```

* Ref1: https://github.com/jruby/jruby/wiki/CallingJavaFromJRuby#subclassing-a-java-class
* Ref2: https://gist.github.com/hiroyuki-sato/972d1b02a1b3407c09795274cf6aa449

This error may relate to the following code.

https://github.com/embulk/embulk/blob/d7be6aadd4e8f284a66e069d07a47f175a06082e/embulk-ruby/lib/embulk/error.rb#L5-L13

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
Hello, @dmikurube 

1. This PR relates to #1505. Could you tell me how to create this PR?

2. Does this comment is sufficient explanation?

As of JRuby 9.3, subclassing a Java classes are full java classes, which introduces some restrictions:
See details:
https://github.com/jruby/jruby/wiki/CallingJavaFromJRuby#subclassing-a-java-class
https://github.com/jruby/jruby/issues/7221

### CODE REVIEW

File: embulk-ruby/lib/embulk/error.rb [hunk 1]
```diff
@@ -1,26 +1,24 @@
...
   # ConfigError is not a ::StandardError but is a java.lang.RuntimeException.
   # "rescue => e" can rescues ConfigError.
   class ConfigError < Java::Config::ConfigException
-    def initialize(message=nil)
-      if message
-        super(message.to_s)
-      else
-        super()
-      end
+    def initialize(*arguments)
```
Comment (dmikurube) [inline embulk-ruby/lib/embulk/error.rb:12]: This signature change may mean that `ConfigError` now accepts varieties of arguments, such as: `ConfigError.new(1, 23.4, RuntimeError.new("some error"))`. Is this correct?

**Review by dmikurube — COMMENTED** [review]
I don't think it'll be included in v0.10.36. Then just wait for #1505 merged.

**Comment by hiroyuki-sato** [comment]
> I don't think it'll be included in v0.10.36. Then just wait for #1505 merged.

OK. Thanks!
I'll add the test results later.

File: embulk-ruby/lib/embulk/error.rb (hunk 1 above)
Comment (dmikurube) [reply embulk-ruby/lib/embulk/error.rb:12]: If then, can you make it rdoc-documented, not for the module `Embulk`, but for these `ClassError` and DataError` classes?

**Review by dmikurube — COMMENTED** [review]
Even if a reader reads "subclassing a Java classes are full java classes, which introduces some restrictions", they won't understand what is the "restrictions", and they are not sure what they need to take care of when using `ConfigError`. It does not help readers/developers with `ConfigError`.

What do you think with the suggestion?  (I moved most of them to rdoc of the `initialize` method, not the class.)

**Comment by hiroyuki-sato** [comment]
@dmikurube Thank you for your review. I used your comment and added the same comment to DataError too.

**Comment by dmikurube** [comment]
Thanks for addressing my comment. As I'm not very confident that it has no problems, let me delay merging this after v0.10.37 (expected to be v0.10.38).

**Comment by dmikurube** [comment]
@hiroyuki-sato v0.10.39 has been out. Let's go with this pull request in the next v0.10.40!

**Review by dmikurube — APPROVED** [review]
LGTM! Thanks for waiting...

**Comment by dmikurube** [comment]
Merging for v0.10.40.
